name: ci
on: [push, pull_request]
env:
  CACHE_PATHS: |
    ~/.cargo/registry
    ~/.cargo/git
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        with:
          path: ${{ env.CACHE_PATHS }}
          key: ${{ hashFiles('Cargo.toml') }}
      - name: Format check
        run: cargo fmt --all --verbose -- --check
      - name: Format check
        run: cargo clippy --workspace --tests -- -Dwarnings
      - name: Build
        run: cargo build
      - name: Run tests
        run: cargo test
