name: release
on: [push, pull_request]
jobs:
  build:
    name: Release binary
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            target: x86_64-unknown-linux-gnu
            artifact_name: wise
            asset_name: wise-x86_64-unknown-linux-gnu
          - os: windows-latest
            target: x86_64-pc-windows-msvc
            artifact_name: wise_windows.exe
            asset_name: wise-x86_64-pc-windows-msvc
          - os: macos-latest
            target: x86_64-apple-darwin
            artifact_name: wise_darwin
            asset_name: wise-x86_64-apple-darwin
    runs-on: ${{ matrix.os }}
    env:
      PKG_CONFIG_PATH: /usr/lib/x86_64-linux-gnu/pkgconfig
      OPENSSL_LIB_DIR: /usr/lib/x86_64-linux-gnu/
      OPENSSL_INCLUDE_DIR: /usr/include/openssl
    steps:
      - name: Install deps
        if: matrix.target == 'x86_64-unknown-linux-gnu'
        run: |
          sudo apt install -qq -y libssl-dev pkg-config
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
      - uses: Swatinem/rust-cache@v1
      - name: Build
        uses: actions-rs/cargo@v1
        with:
          use-cross: true
          command: build
          args: --release --target ${{ matrix.target }} --all-features --verbose
      - name: Upload release binary to release
        uses: svenstaro/upload-release-action@2.1.1
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: target/${{ matrix.target }}/release/${{ matrix.artifact_name }}
          asset_name: ${{ matrix.asset_name }}
          tag: ${{ github.ref }}
          overwrite: true
